### ISSUE TITLE
Feature: Support Regex Pattern

### ISSUE THREAD

**Issue by nogic1008** [ddradar/lgtm-action#20]
## Summery
This action only supports single "LGTM" or "lgtm" comment.
It is useful to be able to change wake up words.

## Usage
```yaml
steps:
  - uses: ddradar/lgtm-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      image-url: "your image"
      # default is ^(LGTM|lgtm)$
      search-pattern: |
        ^lgtm$
        ^(ヨシ|よし|ﾖｼ)(!|！)?$
```
## Tasks
- [x] get multiple input (ref: https://github.com/actions/cache/blob/master/src/restore.ts#L30-L33) (#45)
- [x] fix `isLGTM` function to use `RegExp`
- [x] test
- [x] add `search-pattern` input to `action.yml` (#45)
- [ ] document
